# Generated by Django 4.2 on 2025-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmoLux', '0003_commande_produit_categorie_produit_date_ajout_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur'},
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
