# Generated by Django 4.2 on 2025-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmoLux', '0005_marque_alter_articlepanier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la vidéo descriptive'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix (DH)'),
        ),
    ]
