# Generated by Django 4.2 on 2025-04-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmoLux', '0006_marque_video_url_alter_produit_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marque',
            name='video_url',
        ),
    ]
