# Generated by Django 4.2 on 2025-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmoLux', '0007_remove_marque_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('en_ligne', 'Paiement en ligne'), ('livraison', 'Paiement à la livraison')], default='livraison', max_length=100),
        ),
    ]
